# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='id',
        ),
        migrations.AddField(
            model_name='protocol',
            name='ninstance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(max_length=100, primary_key=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='steps', serialize=False, to='protocol.Protocol'),
        ),
    ]
